<?php
$truncateSettings = [
  'rows' => $this->config()->getRecordAuthorLimit(),
  'top-toggle' => 30,
];
$authorKeys = array_keys($data[$type]);
$lastKey = end($authorKeys);
?>
<?php if (!empty($data[$type])): ?>
  <div class="truncate-authors" data-truncate="<?=$this->htmlSafeJsonEncode($truncateSettings)?>">
    <?php foreach ($data[$type] as $author => $dataFields): ?>
      <span class="author-line"<?=$this->schemaOrg()->getAttributes(['property' => $schemaLabel])?>>
        <a href="<?=$this->record($this->driver)->getLink('author', $author)?>">
          <?=$this->escapeHtml(rtrim($author, ','))?>
        </a>
        <?php
          if (!empty($requiredDataFields)) {
            $that = $this;
            $translate = function ($str) use ($that) {
              return $that->transEsc($str);
            };
            foreach ($requiredDataFields as $field) {
              $name = $field['name'];
              $prefix = $field['prefix'] ?? '';
              if (isset($dataFields[$name])) {
                $props = implode(', ', array_unique(array_map($translate, $dataFields[$name])));
                if (!empty($props)) {
                  echo '<span class="author-property-' . $name . '">(' . $props . ')</span>';
                }
              }
            }
          }
        ?><?php if ($author !== $lastKey): ?>,<?php endif; ?>
      </span>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
