<?php foreach ($this->data as $notation): ?>
    <span class="notationLine">
        <a data-toggle="tooltip" data-placement="right" data-html="true"
           href="<?= $this->record($this->driver)->getLink('dficlassification', $notation, $this->searchClassId) ?>"
           class="searchicon"
           title="<?= $this->transEsc($notation) ?>"><?=$notation?> <?=$this->transEsc('FIV::'.preg_replace('/\s/', '', strtolower($notation))) ?></a>
    </span>
<?php endforeach; ?>