<span class="pull-right">
    <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
</span>
<div id="tagList">
    <?php if (count($this->data) > 0): ?>
        <?php $count = 0; ?>
        <?php foreach ($this->data as $tag): ?><!--
         --><?php if ($count > 0): ?>, <?php endif; ?><!--
          --><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<!--
     --><?php endforeach; ?>
    <?php else: ?>
        <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
    <?php endif; ?>
</div>