<?
    $gnd = isset($info['gnd'][0]) ? $info['gnd'][0] : null;
    $live = isset($info['live'][0]) ? $info['live'][0] : null;
    $role = isset($info['role'][0]) ? $info['role'][0] : null;
    $hiddenFilterString = isset($hiddenFilterString) ? $hiddenFilterString : '';
?>
<a class="<?=$type?>" href="<?=$this->record($this->driver)->getLink('author', $this->name, $this->searchClassId)?>"><?=$this->transEsc($this->name)?><?if (isset($live)):?>, <?=$this->escapeHtml($live)?><? endif; ?></a><? if (!empty($gnd)): ?>
    <a data-placement="right" data-toggle="tooltip" title="<?=$this->transEsc('Search GND-ID')?>: <?=$this->escapeHtml($gnd)?>" class="hidden-print searchLink" href="<?=$this->url('search-results')?>?lookfor=&quot;<?=$this->escapeHtml($gnd)?>&quot;&amp;type=GNDId<?= $hiddenFilterString ?>"></a><span class="visible-print">GND-ID: <?=$this->escapeHtml($gnd)?></span><? endif; ?>
<? if (!empty($role)): ?>, <?=$this->transEsc('CreatorRoles::'.$role)?><? endif; ?>
<?php if(isset($gnd)):?>
<?php $gndLink = $this->gndLink()->fromExplore($gnd); ?>
 <a class="external hasicon" data-toggle="tooltip" title="<?=$this->transEsc('DNB_link')?>" href="<?=$this->escapeHtmlAttr($gndLink)?>">
    <i class="fa fa-info-circle"></i>
</a>
<?php endif ?>
