<a>
    Dies ist eine Teststellung zur Anbindung des Open-Source Discoverysystems <a href="https://wiki.bsz-bw.de/display/BOSS">BOSS</a> an <a href="https://wiki.bsz-bw.de/display/BWFOLIO">FOLIO</a>. BOSS basiert auf <a href="https://vufind.org">VuFind®</a>.
</p>
<p>
    Ziel des vom Ministerium für Wissenschaft, Forschung und Kunst Baden-Württemberg (MWK) geförderten Projektes bwFOLIO ist, aus infrastruktureller Perspektive die Potentiale und Möglichkeiten eines Produktivbetriebs des Open-Source-Bibliotheksmanagementsystems FOLIO in Baden-Württemberg zu bestimmen, sodass im weiteren Projektverlauf den Bibliotheken des Landes Baden-Württemberg das Bibliothekssystem FOLIO vorgestellt werden kann.    <br/>
</p>
<p>
    Bei technischen Fragen und Anregungen: <a href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</p>


