<?php $bibliographies = $this->driver->tryMethod('getBibliographies');
if ($bibliographies != false && count($bibliographies) > 0):
    foreach ($bibliographies as $bib): ?>
        <?php if ($this->client()->is($bib)): ?>
            <span data-toggle="tooltip" title="<?=$this->transEsc($bib . "_label")?>">
            <?= $this->bibliographyIcon($bib) ?>
            </span>
        <?php endif;?>
    <?php endforeach ?>
<?php endif ?>
<?php foreach ($this->driver->getFormats() as $format): ?>
    <?php if ($format == 'Online' || $format == 'E-Book'): ?>
        <?php $labelclass = "label-success"?>
    <?php else: ?>
        <?php $labelclass="label-info"?>
    <?php endif ?>
    <span class="label <?=$labelclass?> <?= $this->record($this->driver)->getFormatClass($format) ?>"><?= $this->transEsc('Formats::'.$format) ?></span>
<?php endforeach; ?>
<?php if ($this->client()->is('wlb_facet_tooltip')): ?>
<?php if ($this->driver->tryMethod('isEPflicht')):?>
        <span class="label label-warning" data-toggle="tooltip" title="<?=$this->transEsc('ePflicht-BW Text')?>"><?=$this->transEsc('ePflicht-BW Label')?></span>
<?php endif ?>
<?php if ($this->driver->tryMethod('isLFER')):?>
        <span class="label label-lfer" data-toggle="tooltip" title="<?=$this->transEsc('LFER_long')?>"><?=$this->transEsc('lizenzfrei')?></span>
<?php endif ?>
<?php endif ?>