<p>Suchen Sie im Katalog Plus der Württembergischen Landesbibliothek nach Büchern, Zeitschriften, Aufsätzen, Karten, Noten und anderen Medien.</p>

<p><b>Wenn Sie nur nach Beständen der Württembergischen Landesbibliothek suchen möchten, nutzen Sie bei Ihren Suchergebnissen den Filter „WLB-Bestand“.</b></p>

<div>
    Sie finden im Katalog Plus folgende Bestände und Sammlungen:
    <ul>
        <li>Württembergische Landesbibliothek</li>
        <li>Landesbibliographie Baden-Württemberg</li>
        <li>Internationale Hölderlin-Bibliographie</li>
        <li>Stefan George-Bibliographie</li>
        <li>Deutsche Pharmazeutische Zentralbibliothek</li>
        <li>wissenschaftliche Bibliotheken aus den Verbundregionen von GBV und SWB (K10plus)</li>
        <li>frei zugängliche Online-Publikationen (Open Access)</li>
        <li>wissenschaftliche Aufsätze aus zahlreichen Datenbanken</li>
    </ul>
</div>

<p>
    Für die gezielte Recherche in der Landesbibliographie Baden-Württemberg und den Bibliographien der Literaturarchive von Stefan George und Friedrich Hölderlin nutzen Sie die Filter bei Ihren Suchergebnissen oder in der Erweiterten Suche.
    Über den Reiter „Fernleihe“ können Medien und einzelne Aufsätze bestellt werden, die nicht im Bestand der WLB sind.
</p>

<p class="alert alert-danger">
    Es handelt sich um eine Beta-Version des neuen Katalog Plus der WLB. Aktuell kann es noch zu Darstellungsproblemen kommen.
    Sollten Sie auf Fehler stoßen, melden Sie diese gerne per Mail an <a href="mailto:katalogplus@wlb-stuttgart.de">katalogplus@wlb-stuttgart.de</a>. Vielen Dank!
</p>
<br>