<?php


// Set page title.
$this->headTitle($this->translate('Libraries') . ': ' . $this->driver->getBreadcrumb());
$content = $this->tab->getContent();
$wlbHasHoldings = false;
?>

<?php if (isset($content) && count($content) > 0): ?>
    <table class="table table-striped table-condensed tablesorter">
        <thead>
        <tr>
            <th class="col-sm-1 col-xs-1 hidden-xs"><?= $this->transEsc('Contact') ?></th>
            <th><?= $this->transEsc('Library') ?></th>
            <th><?= $this->transEsc('Call Number') ?></th>
            <?php if ($this->driver->isJournal()): ?>
                <th><?= $this->transEsc('Collection') ?></th><?php endif; ?>

        </tr>
        </thead>
        <tbody>
        <?php foreach ($content as $result): ?>
            <tr>
                <?php if (is_string($result['isil']) && preg_match('/^[A-Z]{2}-/', $result['isil'])): ?>
                    <?php $wlbHasHoldings = $wlbHasHoldings || ($result['isil'] == 'DE-24'); ?>
                    <td class="hidden-xs">
                        <?php if ($result['isil'] !== 'LFER'): ?>
                            <span class="text-nowrap">
                            <?php if (isset($result['homepage'])): ?>
                                <a data-toggle="tooltip"
                                   title="<?= $this->transEsc('ILL::library_homepage') ?>"
                                   href="<?= $result['homepage'] ?>"
                                   class="external hasicon"><i
                                        class="fa fa-globe"></i><?= $this->escapeHtml($result['isil']) ?></a>
                            <?php else: ?>
                                <?= $this->escapeHtml($result['isil']) ?>
                            <?php endif; ?>
                        </span>
                        <?php else: ?>
                            <?= $this->abbrev($result['isil'], 'LFER_long') ?>
                        <?php endif; ?>
                    </td>

                    <td>
                        <?php if (isset($result['opacurl']) && isset($result['name']) && trim($result['opacurl']) != '' && $this->driver->getNetwork() !== 'ZDB'): ?>
                            <?php $opac = preg_replace('/%PPN%/', $this->driver->getPPN(), $result['opacurl']) ?>
                            <a data-toggle="tooltip"
                               title="<?= $this->transEsc('ILL::library_opac') ?>"
                               href="<?= $opac ?>"
                               class="external hasicon">
                                <i class="fa fa-globe"></i><?= $this->escapeHtml($result['name']) ?>
                            </a>
                        <?php else: ?>
                            <?= isset($result['name']) ? $this->escapeHtml($result['name']) : '' ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if (isset($result['url']) && is_array($result['url'])):
                            $url = array_shift($result['url']);
                            $result['url'] = $url;
                        endif; ?>
                        <?php if (isset($result['call_number']) && is_array($result['call_number'])):
                            $callnumber = implode(', ', $result['call_number']);
                            $result['call_number'] = $callnumber;
                        endif; ?>
                        <?php if (isset($result['call_number']) && !isset($result['url'])): ?>
                            <?= $this->escapeHtml($result['call_number']) ?>
                        <?php elseif (isset($result['url']) && isset($result['call_number'])): ?>
                            <a href="<?= $result['url'] ?>" target="_blank"
                               data-toggle="tooltip"
                               title="<?= $this->transEsc('Fulltext') ?>"><i
                                    class="fa fa-globe"></i><?= $this->escapeHtml($result['call_number']) ?>
                            </a>
                        <?php elseif (isset($result['url'])): ?>
                            <a href="<?= $result['url'] ?>" target="_blank"
                               data-toggle="tooltip"
                               title="<?= $this->transEsc('Fulltext') ?>"><i
                                    class="fa fa-globe"></i><?= $this->transEsc('E-Book') ?>
                            </a>
                        <?php else: ?>
                            <?= $this->transEsc('NoCallnumber') ?>
                        <?php endif; ?>
                    </td>

                    <?php if ($this->driver->isJournal()): ?>
                        <?php if (isset($result['issue']) && is_array($result['issue'])): ?>
                            <td><?= isset($result['issue']) ? $this->escapeHtml(implode(' | ', $result['issue'])) : '' ?></td>
                        <?php else: ?>
                            <td><?= isset($result['issue']) ? $this->escapeHtml($result['issue']) : '' ?></td>
                        <?php endif ?>
                    <?php endif; ?>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">
      $(document).ready(function () {
        $('.tablesorter').tablesorter({
          sortList: [[0, 0]]
        });
      });
    </script>
    <?php if ($this->client()->is('wlb2')): ?>
        <?php if ($this->driver->tryMethod('isArticle')): ?>
            <div><b><em><?= $this->transEsc('check_parent_availability') ?></em></b></div>
        <?php endif; ?>
        <?php if ($this->client()->is('wlb2') && !$wlbHasHoldings): ?>
            <?= $this->render('RecordTab/parts/toillbutton.phtml') ?>
        <?php endif; ?>
    <?php endif; ?>
<?php else: ?>
    <?php if (!$this->client()->is('wlb2')): ?>
        <div><?=$this->transEsc('no_local_hit')?> </div>
    <?php endif; ?>
    <?php if ($this->client()->is('wlb2')): ?>
        <?php if ($this->driver->tryMethod('isArticle')): ?>
            <div><b><em><?= $this->transEsc('check_parent_availability') ?></em></b></div>
        <?php endif; ?>
        <?= $this->render('RecordTab/parts/toillbutton.phtml') ?>
    <?php endif; ?>
<?php endif; ?>
