<?php
//Set page title.
use Bsz\Debug;
use VuFind\XSLT\Processor;

$this->headTitle($this->translate('Staff View') . ': ' . $this->driver->getBreadcrumb());
$content = $this->driver->tryMethod('getGroupField');
?>
<?php if ($content !== false && $content != ''): ?>
    <table class="table citation table-striped">
        <tr>
            <th width="15%">Match-Key</th>
            <td><?=$this->escapeHtmlAttr($content)?></td>
        </tr>
    </table>
<?php endif; ?>
<?= Processor::process('record-marc.xsl', $this->driver->getXML('marc21'))?>

<h3>Solr-Indexfelder</h3>
<table class="citation table table-striped">
    <?php foreach ($this->driver->getRawData() as $field => $values): ?>
        <tr>
            <th width="30%"><?=$this->escapeHtml($field)?></th>
            <td>
                <?php if (!is_array($values)) {
                    $values = [$values];
                } ?>
                <?php foreach ($values as $value): ?>
                    <?=$this->escapeHtml(is_array($value) ? print_r($value, true) : $value)?><br />
                <?php endforeach; ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>