<div>
    <a target="_blank" href="https://verbundwiki.gbv.de/display/VZG/K10plus-Zentral">K10plus-Discovery</a> contains approx. 329.3 million records:<br/><br/>
</div>

<ul>
    <li>approx. 88.7 millions of digital objects and bibliographic references from the <a href="https://www.nationallizenzen.de/" class="external-link"
               rel="nofollow">national licenses </a>
    </li>
    <li>approx. 62.6 million records of the holdings of all GBV libraries (the
        GBV Union Catalog <a class="external-link"
                             href="https://gso.gbv.de/DB=2.1/" rel="nofollow">GVK</a>)
    </li>
    <li>approx. 58.9 million articles from over 24000 journals from the Online
        Contents data (<a href="http://gso.gbv.de/DB=2.3/"
                           class="external-link" rel="nofollow">OLC</a>) with
        proof of ownership from the <a class="external-link"
                                    href="http://www.zeitschriftendatenbank.de/"
                                    rel="nofollow">ZDB</a>
    </li>
    <li>approx. 38.6 million references from the Southwest German Library Network
        (<a href="http://swb.bsz-bw.de" class="external-link"
            rel="nofollow">SWB</a>)</li>
    <li>approx. 39.3 million articles from <a
                href="https://www.ncbi.nlm.nih.gov/pubmed/"
                class="external-link" rel="nofollow">PubMed / Medline</a></li>
    <li>approx. 15.6 million data records from<a
                href="https://de.wikipedia.org/wiki/Fachinformationsdienste_für_die_Wissenschaft"
                class="external-link"
                rel="nofollow">Fachinformationsdiensten</a>
    </li>
    <li>approx. 13.9 million records from <a href="https://www.jstor.org"
                                       class="external-link" rel="nofollow">JSTOR</a>&nbsp
    </li>
    <li>approx. 10.1 million articles and journals from the Directory of Open
        Access Journals (<a href="http://www.doaj.org/" class="external-link"
                            rel="nofollow">DOAJ</a>) under a <a
                href="http://creativecommons.org/licenses/by-sa/4.0/"
                class="external-link" rel="nofollow">Creative Commons BY-SA 4.0
            license</a>&nbsp</li>
    <li>approx. 6.4 million articles from journals published by  <a
                href="https://www.elsevier.com/" class="external-link"
                rel="nofollow">Elsevier</a>
    </li>
    <li>approx. 5.8 million articles from<a href="https://link.springer.com"
                                          class="external-link" rel="nofollow">Springer
            E-Journals</a></li>
    <li>approx. 4.4 million records of the union catalog of public libraries (<a href="https://gso.gbv.de/DB=1.126/"
                         class="external-link" rel="nofollow">ÖVK</a>)
    </li>
    <li>approx. 2.6 million records from <a href="https://arxiv.org/"
                                           class="external-link" rel="nofollow">arXiv</a>
    </li>
    <li>approx. 1.9 million articles from journals published by  <a
                href="https://www.wiley.com" class="external-link"
                rel="nofollow">Wiley</a>
    </li>
    <li>approx. 1.3 million clinical studies from the database<a
                href="http://ClinicalTrials.gov" class="external-link"
                rel="nofollow">ClinicalTrials.gov</a>
    </li>
    <li>approx. 967.000 articles from journals published by De Gruyter <a
                href="https://www.degruyter.com" class="external-link"
                rel="nofollow">De Gruyter</a>
    </li>
   <li>approx. 368.000 records from <a href="https://www.researchsquare.com"
                                      class="external-link" rel="nofollow">Research
            Square</a>
    </li>
    <li>approx. 308.000 records from <a href="https://www.biorxiv.org/"
                                      class="external-link" rel="nofollow">biorXiv</a>
    </li>
    <li>approx. 222.000 records (articles) from OpenEdition <a href="https://www.openedition.org/"
                                                               class="external-link" rel="nofollow">OpenEdition</a>
    </li>
    <li>approx. 68.000 records from <a href="https://www.preprints.org/"
                                     class="external-link" rel="nofollow">preprints.org</a>
    </li>
    <li>approx. 44.000 records from <a href="https://chemrxiv.org/"
                                     class="external-link" rel="nofollow">chemrXiv</a>
    </li>
    <li>approx. 9.000 records from <a href="https://www.techrxiv.org"
                                    class="external-link" rel="nofollow">techrXiv</a>
    </li>
    <li>approx. 3.200 records from <a href="https://engrxiv.org/"
                                   class="external-link"
                                   rel="nofollow">engrXiv</a>
    </li>
</ul>

<div>
    Do you have any technical questions or proposals? Please mail to: <a href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</div>

<div>
    A project to build a joint infrastructure by <a target="_blank" href="https://www.bsz-bw.de">SWB Library Network</a> (BSZ) and  <a target="_blank" href="https://www.gbv.de/Verbundzentrale">GBV Library Network</a> (GBV).<br/><br/>
</div>
