<p>
    This is a testapplication for connecting the open source discovery system <a href="https://wiki.bsz-bw.de/display/BOSS">BOSS</a> to <a href="https://wiki.bsz-bw.de/display/BWFOLIO">FOLIO</a>. BOSS is based on <a href="https://vufind.org">VuFind®</a>.
</p>

<p>
    The aim of the bwFOLIO project, funded by the Baden-Württemberg Ministry of Science, Research and the Arts (MWK), is to determine the potential and possibilities of productive operation of the FOLIO open source library management system in Baden-Württemberg from an infrastructural perspective, so that the FOLIO library system can be presented to the libraries of the state of Baden-Württemberg in the further course of the project.<br/>
</p>

<p>
    For technical questions and suggestions: <a href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</p>