<p><b>ÖFFNUNGSZEITEN: Montag - Freitag 9:00 - 18:00 Uhr</b></p>

<p><b>Änderungen:</b></p>
<p>04.08.25 - 29.08.25 Mo - Fr 9:00 - 14:00 Uhr</p>
<p>01.09.25 - 10.10.25 Mo - Fr 9:00 - 16:30 Uhr</p>
<p>ab 13.10.25 Mo - Fr 9:00 - 18:00 Uhr</p>

<p>Details dazu, welche Medien weiterhin vorbestellt werden müssen, finden Sie auf der <a href="https://bibliothek.ph-gmuend.de/" target="_blank">Website der Bibliothek</a>.</p>

