<p><b>Opening hours: Monday - Friday 9:00 a.m. - 6:00 p.m.</b></p>

<p><b>Changes:</b></p>

<p>24.2.25 - 11.4.25 Mon - Fri 9:00 a.m. - 4:30 p.m</p>
<p>14.4.25 - 8.8.25 Mon - Fri 9:00 a.m. - 6:00 p.m</p>

<p>(Exception: excursion week June 10th - June 13th, 2025 Tue - Fri 9:00 a.m. - 4:30 p.m.)</p>

<p>11.8.25 - 29.8.25 Mon - Fri 9:00 a.m. - 2:00 p.m</p>
<p>01.9.25 - 10.10.25 Mon - Fri 9:00 a.m. - 4:30 p.m</p>
<p>from 13/10/25 Mon - Fri 9:00 a.m. - 6:00 p.m</p>

<p>Details on which media still need to be pre-ordered can be found on the <a href="https://bibliothek.ph-gmuend.de/" target="_blank">library website</a>.</p>
