<?php foreach ($this->data as $item): ?>
    <?php
    $description = '';
    $abbrev = $this->bwlbConcordance($item);
    foreach ($abbrev as $key => $value) {
        $description .= '<tr>';
        $description .= '<td style="text-align:left; padding-right:10px">' . $key . '</td>';
        $description .= '<td style="text-align:left">' . $value . '</td>';
        $description .= '</tr>';
    }
    if (!empty($description)) {
        $header = '<h5>' . $this->transEsc('BWLB') . '</h5>';
        $description = $header . '<table><tbody>' . $description . '</tbody></table>';
    }
    ?>
    <?php if(empty($description)): ?>
        <span class="text-nowrap"><?=$item ?></span>
    <?php else: ?>
        <script>
          var myDefaultWhiteList = $.fn.popover.Constructor.DEFAULTS.whiteList
          myDefaultWhiteList.table = []
          myDefaultWhiteList.tbody = []
          myDefaultWhiteList.tr = []
          myDefaultWhiteList.h5 = []
          myDefaultWhiteList.td = ['style']
        </script>
        <a data-toggle="tooltip" data-placement="right" data-html="true" class="searchicon"
           href="<?= $this->record($this->driver)->getLink('bwlb', $item, $this->searchClassId) ?>"
           title="<?= $this->escapeHtml($description) ?>"><?=$item ?></a>
    <?php endif; ?>
<?php endforeach; ?>